sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install gitbook-cli -g
before_script:
  - git config --global user.name "Feilong Wang"
  - git config --global user.email "i@feilongwang.org"
script:
  - gitbook init
  - git checkout -- SUMMARY.md
  - gitbook build
  - git fetch --depth=50 origin gh-pages
  - git checkout -b gh-pages FETCH_HEAD
  - rm -rf !(_book)
  - cp -rf _book/* .
  - git add -A
  - updated=`date +"%F %T"`
  - git commit -m "Site updated ${updated}"
  - git push --quiet "https://${GH_Token}@${GH_Ref}" HEAD:gh-pages
os:
  - linux
env:
  global:
    - GH_Ref: github.com/feil0n9wan9/android-about-versions-in-chinese.git
